### ISSUE TITLE
使用华南区的存储会报错

### ISSUE THREAD

**Issue by hsu1943** [wishinlife/wp-qiniu#1]
上传的时候报错：
>400:incorrect region, please use up-z2.qiniu.com
感觉应该是jssdk需要升级一下呢

**Comment by xyr5668** [comment]
不是的，作者用的默认的华东区，上传地址是up.qiniu.com，忘记考虑其他区上传地址是有区别的，这个自己应该也能修改

**Comment by hsu1943** [comment]
你知道在哪个地方修改吗？

**Comment by xyr5668** [comment]
就那么几个文件，你点开搜索一下咯

**Comment by JupiterMouse** [comment]
搜索了，但是并没有

**Comment by hsu1943** [comment]
按存储空间修改js文件参考
http://blog.m1910.com/archives/1862.html
